name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker login -uzjh0828 -pzjhA8023 registry.cn-hangzhou.aliyuncs.com && docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/zhangjinhui/`grep "^#" Dockerfile|awk -F"=" '{print $NF}'` && docker push registry.cn-hangzhou.aliyuncs.com/zhangjinhui/`grep "^#" Dockerfile|awk -F"=" '{print $NF}'`
